version: '3'

services:
  app:
    build: .
    ports:
      - "8504:8504"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8504
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8504 