version: '3'

services:
  app:
    build: .
    ports:
      - "8504:8504"
    volumes:
      - .:/app
    depends_on:
      - splash
    environment:
      - SPLASH_URL=http://splash:8050
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8504
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8504

  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    restart: always
    environment:
      - SPLASH_TIMEOUT=60
      - SPLASH_SLOTS=10
      - SPLASH_MAX_TIMEOUT=90
    ulimits:
      nofile:
        soft: 65536
        hard: 65536 