# fly.toml app configuration file generated for earth-cardboard-scraped-app-wild-forest-9940 on 2025-05-03T14:07:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "earth-cardboard-scraped-app"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
  splash = "splash"

[env]
  PORT = "8501"
  SPLASH_URL = "http://localhost:8050"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/app/data"

[[services]]
  internal_port = 8050
  protocol = "tcp"
  processes = ["splash"]

  [[services.ports]]
    port = 8050
    handlers = ["http"]
