app = "earth-cardboard-streamlit"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8504"
  SPLASH_URL = "https://earth-cardboard-splash.fly.dev"

[http_service]
  internal_port = 8504
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "8501"
  SPLASH_URL = "http://earth-cardboard-splash-app.fly.dev"

[mounts]
  source = "data"
  destination = "/app/data"

[[services]]
  internal_port = 8050
  protocol = "tcp"
  processes = ["app"]
  
  [[services.ports]]
    port = 8050
    handlers = ["http"]